version: '3.7'
services:
#  nominatimdb:
  #    build: nominatim/.
  #    ports:
  #      - "6432:5432"
  #    volumes:
  #      - postgresdata:/var/lib/postgresql/11/main
  #      - nominatimdata:/data
  #    entrypoint:
  #      - /app/startpostgres.sh
  #  nominatimapi:
  #    build: nominatim/.
  #    depends_on:
  #      - nominatimdb
  #    environment:
  #      - PGHOST=nominatimdb
  #    ports:
  #      - "7070:8080"
  #    volumes:
  #      - nominatimdata:/data
  #    entrypoint:
  #      - /app/startapache.sh
  app:
    build: panel_app/.
    environment:
      - BOKEH_ALLOW_WS_ORIGIN=${DOCKER_HOST}:5006
      - API_KEY_TOMTOM=${API_KEY_TOMTOM}
      - API_KEY_HERE=${API_KEY_HERE}
    ports:
      - "5006:5006"
    volumes:
      - cache:/usr/src/app/cache/
volumes:
  #  nominatimdata:
  #  postgresdata:
  cache:

